#!/bin/bash -e
# This script squashes the given amount of commits together
# Usage gits {amount-of-commits}

amount=${1}

function checkArgument {
	if [[ ! ${1} =~ ^[0-9]{1,2}$ ]]; then
	    echo "\e[93mGiven argument for amount of commits to squash is invalid, has to be a number\e[0m"
    	exit 1
	fi
	if [[ ${1} < 2 ]]; then
	    echo "\e[93mGiven argument for amount of commits to squash is to small for squashing, has to be > 1\e[0m"
    	exit 1
	fi 
}

# Returns "*" if the current git branch is dirty.
function isDirty {
	echo `git status --porcelain`
}

function checkIsDirty {
	if [[ `isDirty $dir` ]]; then
		echo -e "\e[93mDirectory contains uncommited changes\e[0m"
		exit 3
	fi
}

function checkDirectory {
	if [ ! -d "$PWD/.git" ]; then
		echo -e "\e[93mgits has to be called inside a git directory\e[0m"
		exit 2
	fi
}

checkArgument ${amount}
checkDirectory
checkIsDirty

git reset --soft HEAD~${amount} && 
git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"

